# Site settings
title: "#OurAAPIVote"
email: info@18mr.org
description: > # this means to ignore newlines until "baseurl:"
  Activating Asian Pacific America
baseurl: ""
url: "http://vote.18mr.org" # the base hostname & protocol for your site
twitter_username: 18millionrising
github_username:  18mr
github_projectname: vote

# Build settings
markdown: kramdown
highlighter: rouge

permalink: title
categories: [forvoters, ourvotesmatter, about, general]

plugins: [jekyll-paginate]

# Output
permalink: /:year/:month/:title.html
paginate: 8