# Site settings
title: Elections 2014
email: info@18mr.org
description: > # this means to ignore newlines until "baseurl:"
  Activating Asian Pacific America
baseurl: ""
url: "http://vote.18mr.org" # the base hostname & protocol for your site
twitter_username: 18millionrising
github_username:  catachresis

# Build settings
markdown: kramdown
highlighter: rouge

permalink: title
categories: [forpartners, forvoters, ourvotesmatter, about, general]